#39 add test, flow, core modules + up version
icerockdev/moko-paging pull request #60
Opened 2022-06-03 05:26 UTC by kramlex

2022-06-03 06:00 UTC, Alex009 requested changes

2022-06-03 14:27 UTC, kramlex commented on paging-state/src/commonMain/kotlin/dev/icerock/moko/paging/state/ResourceState.kt
> +sealed interface ResourceState<out T, out E> {
mvvm-state depend on moko-livedata

2022-06-03 15:42 UTC, kramlex commented on paging-state/src/commonMain/kotlin/dev/icerock/moko/paging/state/PagingDataState.kt
> +sealed interface PagingDataState<T> {
removed

2022-06-05 07:22 UTC, Alex009 commented on paging-state/src/commonMain/kotlin/dev/icerock/moko/paging/state/ResourceState.kt
> +sealed interface ResourceState<out T, out E> {
so we should extract livedata dependency from mvvm-state...we will have `mvvm-state`, `mvvm-state-livedata`, `mvvm-state-flow`

2022-06-05 07:25 UTC, kramlex commented on paging-state/src/commonMain/kotlin/dev/icerock/moko/paging/state/ResourceState.kt
> +sealed interface ResourceState<out T, out E> {
should I use [these](https://github.com/icerockdev/moko-mvvm/pull/152) changes?

2022-06-05 07:27 UTC, Alex009 commented on paging-state/src/commonMain/kotlin/dev/icerock/moko/paging/state/ResourceState.kt
> +sealed interface ResourceState<out T, out E> {
yes, if you can do this comment - https://github.com/icerockdev/moko-mvvm/pull/152#discussion_r668954258

2026-06-30 06:33 UTC, ExNDY commented
Closing in favor of #66

2026-06-30 06:33 UTC, closed without merging